version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:5001"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:5002"
    env_file:
      - ./backend/.env.production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5003"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    nginx:
      build: ./.nginx
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend
        - frontend
        
volumes:
  postgres-data:
  pgadmin-data:

